version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5431:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql  
    restart: always

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "matheus@email.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "54321:80"
    depends_on:
      - postgres
    restart: always
    
  # web:
  #   build: .
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
    
