name: EC2-Deploy

on:
  workflow_call:

jobs:
  EC2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: api_go
          
      - name: Deploy SSH EC2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}
          EXCLUDE: "postgres-data"

      - name: Connect SSH instance EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export HOST=${{ secrets.DB_HOST }}
            export USER=${{ secrets.DB_USER }}
            export PASSWORD=${{ secrets.DB_PASSWORD }}
            export DBNAME=${{ secrets.DB_NAME }}
            export DBPORT=${{ secrets.DB_PORT }}
            export PORT=8080
            chmod +x main
            nohup ./main > nohup.out 2> nohup.err < /dev/null &
            

      

        
