name: go-server

on:
  push: 
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
    
jobs:
  Build-DB:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'ubuntu-20.04' ]
        go_version: [ '>=1.21' ]
    steps:
      - uses: actions/checkout@v3

      - name: Configurando o Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build Database
        run: docker compose build

      - name: Create Database
        run: docker compose up -d

      - name: Build
        run: go build -v main.go

  # Build-App:
  #   needs: Build-DB
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
      
