name: go-server

on: [push]

jobs:
  test-DB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurando o Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.X"

      - name: Build Database
        run: docker compose build

      - name: Create Database
        run: docker compose up -d

  Build:
    needs: test-DB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalando dependencias
        run: go get .

      - name: Build
        run: go build -v main.go
