name: go-server

on:
  push: 
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
    
jobs:
  Build-DB:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ '>=1.21' ]
    steps:
      - uses: actions/checkout@v3

      - name: Configurando o Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build Database
        run: docker compose build

      - name: Create Database
        run: docker compose up -d

      - name: Build
        run: go build -v main.go

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: api_go
          path: main

  docker:
    needs: Build-DB
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
 
  Deploy-EC2:
    needs: Build-DB
    uses: ./.github/workflows/EC2.yml
    secrets: inherit

  # Build-App:
  #   needs: Build-DB
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
      
