name: go-server

on: [push]

jobs:
  Build-DB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurando o Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build Database
        run: docker compose build

      - name: Create Database
        run: docker compose up -d

  Build-App:
    needs: Build-DB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Preparing Go
        run: go get .

      - name: Build
        run: go build -v main.go
