name:  go-server

on: [push]

jobs: 
    build:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v3

        - name: Configurando o Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21.X'

        - name: Build
          run: go run main.go
        